name: myzukrainy
description: A new Flutter project.

version: 1.0.3+3

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.4
  flutter_lints: 1.0.4
  flutter_bloc: 7.0.1
  koin_flutter: 0.11.0-nullsafety.0
  koin: 0.15.0-nullsafety.0
  koin_bloc: 0.2.0-nullsafety.0
  shared_preferences: 2.0.13
  google_fonts: 2.3.1
  easy_localization: 3.0.0
  just_audio: 0.9.20
  audio_service: 0.18.4
  flutter_share: 2.0.0
  lottie: 1.2.2
  rxdart: 0.27.3
  sleek_circular_slider: 2.0.1
  volume_controller: 2.0.3
  dio: 4.0.6
  url_launcher: 6.0.20
  connectivity_plus: 2.3.0
  swagger_dart_code_generator: ^2.4.9

flutter:
  assets:
    - assets/translations/
    - assets/images/
  uses-material-design: true

