name: myzukrainy
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.4
  flutter_lints: 1.0.4
  flutter_bloc: 7.0.1
  koin_flutter: 0.11.0-nullsafety.0
  koin: 0.15.0-nullsafety.0
  koin_bloc: 0.2.0-nullsafety.0
  shared_preferences: 2.0.13
  google_fonts: 2.3.1
  easy_localization: 3.0.0
  just_audio: 0.9.20
  audio_service: 0.18.4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/images/
    - assets/translations/
  uses-material-design: true

